### ISSUE TITLE
Various Run errors - Help needed

### ISSUE THREAD

**Issue by noto10** [opentimestamps/opentimestamps-client#146]
I installed using pip in Python 3.13.0 for Windows. Installation went well without errors. However, I get the following errors when I tried to run it:

```
C:\Program Files\Python313\Scripts>ots
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python313\Scripts\ots.exe\__main__.py", line 4, in <module>
    from otsclient.ots import main
  File "C:\Program Files\Python313\Lib\site-packages\otsclient\ots.py", line 15, in <module>
    import otsclient.args
  File "C:\Program Files\Python313\Lib\site-packages\otsclient\args.py", line 24, in <module>
    import otsclient.cmds
  File "C:\Program Files\Python313\Lib\site-packages\otsclient\cmds.py", line 23, in <module>
    import bitcoin.rpc
  File "C:\Program Files\Python313\Lib\site-packages\bitcoin\rpc.py", line 38, in <module>
    from bitcoin.wallet import CBitcoinAddress, CBitcoinSecret
  File "C:\Program Files\Python313\Lib\site-packages\bitcoin\wallet.py", line 23, in <module>
    import bitcoin.core.key
  File "C:\Program Files\Python313\Lib\site-packages\bitcoin\core\key.py", line 27, in <module>
    _ssl = ctypes.cdll.LoadLibrary(
        ctypes.util.find_library('ssl.35') or ctypes.util.find_library('ssl') or ctypes.util.find_library('libeay32')
    )
  File "C:\Program Files\Python313\Lib\ctypes\__init__.py", line 471, in LoadLibrary
    return self._dlltype(name)
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Program Files\Python313\Lib\ctypes\__init__.py", line 380, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

C:\Program Files\Python313\Scripts>ots stamp readme.txt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python313\Scripts\ots.exe\__main__.py", line 4, in <module>
    from otsclient.ots import main
  File "C:\Program Files\Python313\Lib\site-packages\otsclient\ots.py", line 15, in <module>
    import otsclient.args
  File "C:\Program Files\Python313\Lib\site-packages\otsclient\args.py", line 24, in <module>
    import otsclient.cmds
  File "C:\Program Files\Python313\Lib\site-packages\otsclient\cmds.py", line 23, in <module>
    import bitcoin.rpc
  File "C:\Program Files\Python313\Lib\site-packages\bitcoin\rpc.py", line 38, in <module>
    from bitcoin.wallet import CBitcoinAddress, CBitcoinSecret
  File "C:\Program Files\Python313\Lib\site-packages\bitcoin\wallet.py", line 23, in <module>
    import bitcoin.core.key
  File "C:\Program Files\Python313\Lib\site-packages\bitcoin\core\key.py", line 27, in <module>
    _ssl = ctypes.cdll.LoadLibrary(
        ctypes.util.find_library('ssl.35') or ctypes.util.find_library('ssl') or ctypes.util.find_library('libeay32')
    )
  File "C:\Program Files\Python313\Lib\ctypes\__init__.py", line 471, in LoadLibrary
    return self._dlltype(name)
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Program Files\Python313\Lib\ctypes\__init__.py", line 380, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

Can anyone help?

**Comment by briporteran** [comment]
I encountered this error and the issue was that I didn't have OpenSLL libraries in my path. Note that the bitcoin lib is using an older version of OpenSSL so you can't just download the latest OpenSLL lib and use that (it's a completely different name than the lib's listed in this line "File "C:\Program Files\Python313\Lib\site-packages\bitcoin\core\key.py", line 27, in <module>
    _ssl = ctypes.cdll.LoadLibrary(
        ctypes.util.find_library('ssl.35') or ctypes.util.find_library('ssl') or ctypes.util.find_library('libeay32')
    )") 
I also downgraded my python version to 3.11 (but I don't think that had anything to do with the above issue)

**Comment by kai339** [comment]
?
