### ISSUE TITLE
openssl removed ripemd160

### ISSUE THREAD

**Issue by RCasatta** [opentimestamps/opentimestamps-client#148]
openssl removed ripemd160 which is used by our library to verify for example `hello-world.txt.ots`

```
$ ots verify examples/hello-world.txt.ots 
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/casatta/.local/bin/ots", line 8, in <module>
    sys.exit(main())
  File "/home/casatta/.local/lib/python3.10/site-packages/otsclient/ots.py", line 34, in main
    args.cmd_func(args)
  File "/home/casatta/.local/lib/python3.10/site-packages/otsclient/cmds.py", line 446, in verify_command
    detached_timestamp = DetachedTimestampFile.deserialize(ctx)
  File "/home/casatta/.local/lib/python3.10/site-packages/opentimestamps/core/timestamp.py", line 337, in deserialize
    timestamp = Timestamp.deserialize(ctx, file_hash)
  File "/home/casatta/.local/lib/python3.10/site-packages/opentimestamps/core/timestamp.py", line 181, in deserialize
    do_tag_or_attestation(tag)
  File "/home/casatta/.local/lib/python3.10/site-packages/opentimestamps/core/timestamp.py", line 168, in do_tag_or_attestation
    result = op(initial_msg)
  File "/home/casatta/.local/lib/python3.10/site-packages/opentimestamps/core/op.py", line 135, in __call__
    r = self._do_op_call(msg)
  File "/home/casatta/.local/lib/python3.10/site-packages/opentimestamps/core/op.py", line 292, in _do_op_call
    r = hashlib.new(self.HASHLIB_NAME, bytes(msg)).digest()
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
```

**Comment by petertodd** [comment]
This actually should be an issue on the upstream python-opentimestamps repo. I've opened a new issue for it: https://github.com/opentimestamps/python-opentimestamps/issues/49
