### ISSUE TITLE
info subcommand fails with bad arg `verbosity`

### ISSUE THREAD

**Issue by ankostis** [opentimestamps/opentimestamps-client#42]
When running `./ots info foo.ots` I get this exception:

```
File sha256 hash: 2b1d2e7d12b239beec8d02379e32ad974383c357c0b96ba301ef89af142a6de0
Timestamp:
Traceback (most recent call last):
  File "./ots", line 36, in <module>
    args.cmd_func(args)
  File "D:\Work\ots-client.git\otsclient\cmds.py", line 501, in info_command
    print(detached_timestamp.timestamp.str_tree(verbosity=args.verbosity))
TypeError: str_tree() got an unexpected keyword argument 'verbosity'```

**Comment by petertodd** [comment]
Huh, that's really odd... What's your PYTHONPATH?

Sounds like your setup is somehow using the incorrect python-opentimestamps version.
