### ISSUE TITLE
Client is failing when some callendar is unavailable ...

### ISSUE THREAD

**Issue by rtraba** [opentimestamps/opentimestamps-client#96]
Client is failing when some callendar is unavailable ...
Submitting to remote calendar https://a.pool.opentimestamps.org <<<< not reponding
Submitting to remote calendar https://b.pool.opentimestamps.org << working fine
Submitting to remote calendar https://a.pool.eternitywall.com <<<<  working fine
Submitting to remote calendar https://ots.btc.catallaxy.com <<< not reponding

See this:
#########################################################
/opts/opentimestamps-client/examples$ ots -v stamp lalal
Submitting to remote calendar https://a.pool.opentimestamps.org
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1252, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rodrigo/opts/opentimestamps-client/ots", line 34, in <module>
    args.cmd_func(args)
  File "/home/rodrigo/opts/opentimestamps-client/otsclient/cmds.py", line 128, in stamp_command
    create_timestamp(merkle_tip, args.calendar_urls, args.setup_bitcoin if args.use_btc_wallet else False)
  File "/home/rodrigo/opts/opentimestamps-client/otsclient/cmds.py", line 98, in create_timestamp
    calendar_timestamp = remote.submit(timestamp.msg)
  File "/home/rodrigo/opts/opentimestamps-client/opentimestamps/calendar.py", line 36, in submit
    with urllib.request.urlopen(req) as resp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
rodrigo@rodrigo-ayi-notebook:~/opts/opentimestamps-client/examples$
#########################################################

But if I try with -c option it works fine
#########################################################
~/opts/opentimestamps-client/examples$ ots -v stamp -c https://a.pool.eternitywall.com lalal
Submitting to remote calendar https://a.pool.eternitywall.com

~/opts/opentimestamps-client/examples$ ots info lalal.ots 
File sha256 hash: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Timestamp:
append 958a3527b7cbf948ab06ed0e76a20961
sha256
append 43d745f28f3ca3f54ab54f1195fcdfb7
sha256
append 060be7b6d2e2f0fe496cc16570385352
sha256
prepend 5b885c97
append 8bf6fcc9b329913d
verify PendingAttestation('https://finney.calendar.eternitywall.com')

~/opts/opentimestamps-client/examples$ 
#########################################################

Is there some response validation on calendar server availability to prevent this error????

**Comment by petertodd** [comment]
Huh, that's very strange. I just tried to reproduce that on my setup, and even though the two servers are down for me, my version completes the timestamp just fine.

What does `ots --version` report for you?

**Comment by rtraba** [comment]
~/opts/opentimestamps-client$ ots --version
v0.2.0

**Comment by petertodd** [comment]
Ah! That's a very old version; current is v0.6.0

IIRC we fixed a bug along those lines in a prior version.

On August 31, 2018 12:32:51 PM UTC, Rodrigo Taba <notifications@github.com> wrote:
>~/opts/opentimestamps-client$ ots --version
>v0.2.0

-- 
https://petertodd.org 'peter'[:-1]@petertodd.org

**Comment by rtraba** [comment]
it's working fine in v0.6.0 ... 
sorry, it was my error to use an obsolte version. 
Thanks Peter, best regards
